title: Dayda
name: Export-Import Bank of the US
description: >-
  This is a catalog of datasets organized and made more accessible from the
  Export-Import Bank of the US, providing simple dowloadable CSV and JSON files,
  as well as Postman Collections you can use as part of workflows and other
  automation.
about: This is all about the entity.
source_url: 'http://example.com'
source_contact_type: general
source_phone: +1 555-555-5555
source_email: info@example.com
source_catalog: data.gov
profile_pic: >-
  https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Seal_of_the_United_States_Export-Import_Bank.svg/721px-Seal_of_the_United_States_Export-Import_Bank.svg.png
favicon: /assets/img/favicon.png
url: 'http://export-import-bank-of-the-us.dayda.org'
encoding: utf-8
paginate: 25
paginate_path: '/page:num/'
markdown: kramdown
